MESSAGES:
  START_MSG: |
    Howdy! ğŸ‘‹
    
    Please note that this bot is still in trial.
    
    This is a simple bot that brings dictionary to your Telegram. ğŸ¤–
    
    Send a normal message with
    `define <space> <your word>`
    syntax to see the magic. ğŸª„

    Send `/help` anytime to refresh your memory ;)

  HELP_MSG: |
    Howdy! ğŸ‘‹

    This is a simple bot that brings dictionary to your Telegram. ;) ğŸ¤–

    Send a normal message with
    `define <space> <your word>`
    syntax to see the magic. ğŸª„

  DEFINE_ERR: |
    Define is not a command â—

    Use the following syntax in a normal message:
    `define <space> <yourword>`

  WORD_ERR: |
    Your word is invalidâ— Try a different word.

  EDITS_REPLY: |
    I do not care about edited messages. ğŸ˜›

  UNRECOGNIZED: |
    beep. bop. beep. ğŸ¤–

    I couldn't understand you.
    Send `/help` to know the proper syntax.
  
  ATTACHMENTS_ERR: |
    Attachments aren't supported, my friend.

  PHONETICS_MSG: |
    *{defined_word}*
    _{phonetic_txt}_ [ğŸ”Š]({phonetic_audio})

  DEFINITION_MSG: |
    *Part of Speech:*
    {part_of_speech}

    *Definition:*
    {definition}

    *Example:*
    {example}