MESSAGES:
  START_CMD: |
    Howdy! ğŸ‘‹
    
    This is a simple bot that brings dictionary to your Telegram. ğŸ¤–
    
    Send a normal message with the following syntax to see the magic. ğŸª„
    `define <space> <your word>`

    Send `/help` anytime to refresh your memory ;)

  HELP_CMD: |
    Howdy! ğŸ‘‹

    This is a simple bot that brings dictionary to your Telegram. ;) ğŸ¤–

    Send a normal message with the following syntax to see the magic. ğŸª„
    `define <space> <your word>`
    
  DEFINE_CMD: |
    Define is not a command â—

    Use the following syntax to send a message:
    `define <space> <yourword>`

  PHONETICS_MSG: |
    *{defined_word}*
    _{phonetic_txt}_ [ğŸ”Š]({phonetic_audio})

  DEFINITION_MSG: |
    *Part of Speech:*
    {part_of_speech}

    *Definition:*
    {definition}

    *Example:*
    {example}

  INVALID_ERR: |
    Your word is invalidâ— Try a different word.

  EDIT_ERR: |
    I do not care about edited messages. ğŸ˜›

  UNRECOGNIZED_ERR: |
    beep. bop. beep. ğŸ¤–

    I couldn't understand you.
    Send `/help` to know the proper syntax.
  
  ATTACHMENT_ERR: |
    Attachments aren't supported, my friend.

  APP_ERR: |
    Seems like something's wrong. Drop me a message at @cryptic_code and I will fix it ASAP.